### ISSUE TITLE
Bug in cell animation

### ISSUE THREAD

**Issue by ArtworkAD** [bfeher/BFPaperTableViewCell#10]
I was using v1.3.1 in my custom table view cell without any problem like this:

    self.usesSmartColor = false
    self.tapCircleColor = UIColor(netHex: 0xff95bc)
    self.backgroundFadeColor = UIColor(netHex: 0xff95bc)
    self.letBackgroundLinger = true

Now I upgraded to 2.1.17 and there is a problem. When you tap on a cell it animates like expected, then the circle disappears. Instead the cell's background color is now completely covered by tapCircleColor.

Just as a tip, to help trace down such problems it is good practice to maintain a CHANGELOG.md and list changes as well as breaking changes in your code.

**Comment by bfeher** [comment]
Hello!
Thanks for the report. 

Without a screenshot I can't fully understand your situation, though I suspect that it has something to do with this new feature/property:

`BOOL alwaysCompleteFullAnimation`

`A BOOL flag indicating whether or not to always complete a full animation cycle (bg fade in, tap-circle grow and burst, bg fade out) before starting another one. NO will behave just like the other BFPaper controls, tapping rapidly spawns many circles which all fade out in turn. Default is YES.`

I hope that setting this new property to NO will solve your problem. 

You are totally right about a changelog! I guess I've been too lazy to keep one abs also never really expected anybody to use my libraries, but those are bad excuses and I'll start using a changelog. Thanks :)

**Comment by ArtworkAD** [comment]
@bfeher appreciate your help. I just updated my colors and now everything is fine. This was not a bug.
