### ISSUE TITLE
Issues drawing a custom border

### ISSUE THREAD

**Issue by ArtworkAD** [bfeher/BFPaperTableViewCell#13]
@bfeher hello again :)

I have a problem drawing a bottom border in my subclassed BFPaperTableViewCell:
```
override func drawRect(rect: CGRect) {

    if self.drawBorder {    
        var context = UIGraphicsGetCurrentContext()
        CGContextMoveToPoint(context, CGRectGetMinX(rect), CGRectGetMaxY(rect))
        CGContextAddLineToPoint(context, CGRectGetMaxX(rect), CGRectGetMaxY(rect))
        CGContextSetStrokeColorWithColor(context, UIColor(netHex: 0xEFEEF4).CGColor)
        CGContextSetLineWidth(context, 2)
        CGContextStrokePath(context)
    }
}
```

this works. But as soon as I touch the cell the border disappears. Do you have any idea how to fix this?

**Comment by bfeher** [comment]
Hmm I will take a look, but nothing comes to mind initially. I admittedly haven't tested the control using drawRect.

**Comment by bfeher** [comment]
I tried your code (in objective-c) and I couldn't reproduce the problem :/
![cell-drawrect-test](https://cloud.githubusercontent.com/assets/3466708/7243626/80d7a02e-e80a-11e4-8152-594b6fe99b2f.gif)

**Comment by bfeher** [comment]
![cell-drawrect-test](https://cloud.githubusercontent.com/assets/3466708/7243697/65dbc5f6-e80b-11e4-8b2d-f67112dddbc9.png)

**Comment by ArtworkAD** [comment]
@bfeher I found the problem. Set

    cell.tapCircleColor = UIColor.greenColor()
    cell.backgroundFadeColor = UIColor.whiteColor()

Obviously the backgroundFadeColor eats the border :laughing:  When I set

    cell.backgroundFadeColor = UIColor.clearColor()

the problem is solved for me.

**Comment by bfeher** [comment]
I'm happy to hear that you got it working :)
Let me know if you find anything else, thanks!
